{"level":"fatal","message":"Error fatal"}
{"level":"error","message":"Error log"}
{"level":"fatal","message":"{\n     \"name\": \"Error\",\n     \"message\": \"Internal server Error\",\n     \"stack\": \"Error: Internal server Error\\n    at CustomError.createError (file:///C:/Users/agusf/Documents/Coderhouse/Backend/Clase%201/clase%2037/desafio/src/utils/CustomError.js:5:23)\\n    at sendMail (file:///C:/Users/agusf/Documents/Coderhouse/Backend/Clase%201/clase%2037/desafio/src/controller/PasswordController.js:44:32)\\n    at Layer.handle [as handle_request] (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at next (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\route.js:149:13)\\n    at Route.dispatch (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\route.js:119:3)\\n    at Layer.handle [as handle_request] (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:284:15\\n    at Function.process_params (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:346:12)\\n    at next (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:280:10)\\n    at Function.handle (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:175:3)\"\n}"}
{"level":"fatal","message":"{\n     \"name\": \"Error\",\n     \"message\": \"Internal server Error\",\n     \"stack\": \"Error: Internal server Error\\n    at CustomError.createError (file:///C:/Users/agusf/Documents/Coderhouse/Backend/Clase%201/clase%2037/desafio/src/utils/CustomError.js:5:23)\\n    at sendMail (file:///C:/Users/agusf/Documents/Coderhouse/Backend/Clase%201/clase%2037/desafio/src/controller/PasswordController.js:45:32)\\n    at Layer.handle [as handle_request] (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at next (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\route.js:149:13)\\n    at Route.dispatch (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\route.js:119:3)\\n    at Layer.handle [as handle_request] (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:284:15\\n    at Function.process_params (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:346:12)\\n    at next (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:280:10)\\n    at Function.handle (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:175:3)\"\n}"}
{"level":"fatal","message":"{\n     \"name\": \"Error\",\n     \"message\": \"Internal server Error\",\n     \"stack\": \"Error: Internal server Error\\n    at CustomError.createError (file:///C:/Users/agusf/Documents/Coderhouse/Backend/Clase%201/clase%2037/desafio/src/utils/CustomError.js:5:23)\\n    at sendMail (file:///C:/Users/agusf/Documents/Coderhouse/Backend/Clase%201/clase%2037/desafio/src/controller/PasswordController.js:46:32)\\n    at Layer.handle [as handle_request] (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at next (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\route.js:149:13)\\n    at Route.dispatch (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\route.js:119:3)\\n    at Layer.handle [as handle_request] (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:284:15\\n    at Function.process_params (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:346:12)\\n    at next (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:280:10)\\n    at Function.handle (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:175:3)\"\n}"}
{"level":"fatal","message":"{\n     \"name\": \"Error\",\n     \"message\": \"Internal server Error\",\n     \"stack\": \"Error: Internal server Error\\n    at CustomError.createError (file:///C:/Users/agusf/Documents/Coderhouse/Backend/Clase%201/clase%2037/desafio/src/utils/CustomError.js:5:23)\\n    at sendMail (file:///C:/Users/agusf/Documents/Coderhouse/Backend/Clase%201/clase%2037/desafio/src/controller/PasswordController.js:47:32)\\n    at Layer.handle [as handle_request] (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at next (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\route.js:149:13)\\n    at Route.dispatch (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\route.js:119:3)\\n    at Layer.handle [as handle_request] (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:284:15\\n    at Function.process_params (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:346:12)\\n    at next (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:280:10)\\n    at Function.handle (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:175:3)\"\n}"}
{"level":"fatal","message":"{\n     \"name\": \"Error\",\n     \"message\": \"Internal server Error\",\n     \"stack\": \"Error: Internal server Error\\n    at CustomError.createError (file:///C:/Users/agusf/Documents/Coderhouse/Backend/Clase%201/clase%2037/desafio/src/utils/CustomError.js:5:23)\\n    at sendMail (file:///C:/Users/agusf/Documents/Coderhouse/Backend/Clase%201/clase%2037/desafio/src/controller/PasswordController.js:49:32)\\n    at Layer.handle [as handle_request] (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at next (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\route.js:149:13)\\n    at Route.dispatch (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\route.js:119:3)\\n    at Layer.handle [as handle_request] (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:284:15\\n    at Function.process_params (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:346:12)\\n    at next (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:280:10)\\n    at Function.handle (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:175:3)\"\n}"}
{"level":"fatal","message":"{\n     \"name\": \"Error\",\n     \"message\": \"Internal server Error\",\n     \"stack\": \"Error: Internal server Error\\n    at CustomError.createError (file:///C:/Users/agusf/Documents/Coderhouse/Backend/Clase%201/clase%2037/desafio/src/utils/CustomError.js:5:23)\\n    at resetPassword (file:///C:/Users/agusf/Documents/Coderhouse/Backend/Clase%201/clase%2037/desafio/src/controller/PasswordController.js:132:32)\\n    at Layer.handle [as handle_request] (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at next (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\route.js:149:13)\\n    at Route.dispatch (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\route.js:119:3)\\n    at Layer.handle [as handle_request] (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:284:15\\n    at param (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:365:14)\\n    at param (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:376:14)\\n    at Function.process_params (C:\\\\Users\\\\agusf\\\\Documents\\\\Coderhouse\\\\Backend\\\\Clase 1\\\\clase 37\\\\desafio\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:421:3)\"\n}"}
{"level":"fatal","message":"{\n     \"name\": \"Error\",\n     \"message\": \"Error al actualizar el rol del usuario\",\n     \"stack\": \"Error: Error al actualizar el rol del usuario\\n    at CustomError.createError (file:///C:/Users/agusf/Documents/Coderhouse/Backend/Clase%201/clase%2037/desafio/src/utils/CustomError.js:5:23)\\n    at cambiarRol (file:///C:/Users/agusf/Documents/Coderhouse/Backend/Clase%201/clase%2037/desafio/src/controller/UserController.js:32:32)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\"\n}"}
{"level":"error","message":"Error al conectar a DB: querySrv ETIMEOUT _mongodb._tcp.cluster0.zvgrerx.mongodb.net"}
